#!/usr/bin/env python3
import sys
import os

# Usage: Usage: python setup_NGP.py <num_repeats>
if len(sys.argv) != 3:
    print("Usage: python setup_NGP.py <num_repeats> <seed_pdb>")
    sys.exit(1)

try:
    num_repeats = int(sys.argv[1])
except ValueError:
    sys.exit("Error: num_repeats must be an integer")

if not os.path.exists(sys.argv[2]):
    FileNotFoundError(f"The file '{sys.argv[2]}' does not exist.")
    #sys.exit("Error: seed_pdb must be a valid file")   
else:
    seed_pdb = sys.argv[2]
    print(f"Using {seed_pdb} as a source of coordinates")

num_sugars = num_repeats*2
num_resi = num_sugars + 1

pg_name = f"l{num_sugars}"

fn, ext = os.path.splitext(os.path.basename(seed_pdb))
exportdir = f"{fn}_export"
if not os.path.exists(exportdir):
    os.makedirs(exportdir)
    print(f"Made directory: {exportdir}")
else:
    print(f"Directory {exportdir} exists")
exportfn = f"{fn}_{pg_name}"

print(f"Preparing str files for {pg_name}")
#tcl_path = os.path.join(REF_parentdir, f"build_{pg_name}.tcl")

seq_filename = f"custom_files/{pg_name}_seq.str"
patch_filename = f"custom_files/{pg_name}_patch.str"

vars_txt = f"""*Information about system
*
set PGNAME = {pg_name}
set SEQFILENAME = {seq_filename}
set PATCHFILENAME = {patch_filename}
set NUMREPEATS = {num_repeats}
set NUMSUGARS = {num_sugars}
set PDBFILENAME = {seed_pdb}
set EXPORTDIR = {exportdir}
set EXPORTFN = {exportfn}
"""

GLY_lines = []
PEP_lines = []
patch_lines = []
for j in range(2, num_repeats+1):

    GLY_lines.append("BNAM BNAG")
    PEP_lines.append(f"""
! Read peptide stem {j} sequence 
read sequence card
* Peptide sequence
*
4
ADGG MDAP DALA DALA
generate PA{j:02} first none last CTER setup warn
                     
""")

    patch_lines.append(f"""! Apply patches for L{2*j}
patch 14BB   GLY {2*j-1}  GLY {2*j}  setup warn
patch 14BB   GLY {2*j}  GLY {2*j+1}  setup warn
patch 3BMDPx GLY {2*j}  PA{j:02} 1  setup warn
    """)

GLY_lines = "\n".join(GLY_lines)
PEP_lines = "\n".join(PEP_lines)
patch_lines = "\n".join(patch_lines)

seq_txt = f"""* Stream file for {pg_name}, {num_repeats} repeats
* Generated by setup_NGP.py

!read GLY
read sequence card
* Glycan Sequence
{num_resi}
UNDP ANAM BNAG
{GLY_lines}
generate GLY setup first none last none

! Read peptide stem 1 sequence 
read sequence card
* Peptide sequence
*
4
ADGG MDAP DALA DALA
generate PA01 first none last CTER setup warn

{PEP_lines}
"""

patch_txt = f"""
!Apply patches for L2
patch LLLX GLY 2 GLY 1 setup warn
patch 14BB GLY 2 GLY 3 setup warn
patch 3BMDPx GLY 2 PA01 1 setup warn

{patch_lines}
"""

coor_txt = f"""
open read unit 10 card name {seed_pdb}
read coor pdb unit 10 resid sele segid GLY .or. segid PA01 end
close unit 10
"""

# Write to vars.str
with open("pg_vars.str", "w") as f:
    f.write(vars_txt)
print(f"Wrote pg_vars.str")

# Write sequence to str
with open(seq_filename, "w") as f:
    f.write(seq_txt)
print(f"Wrote {seq_filename}")

# Write sequence to str
with open(patch_filename, "w") as f:
    f.write(patch_txt)
print(f"Wrote {patch_filename}")



