#!/usr/bin/env python3
"""
setup_sim.py  —  Unified setup for NPG + protein assembly simulations.

Usage:
    python setup_sim.py <sim_folder>

Expected contents of <sim_folder>:
    *_cg.psf / *_cg.crd          protein component (CHARMM-GUI output)
    *_donor_l<N>.pdb              donor  PG strand  (optional)
    *_acceptor_l<N>.pdb           acceptor PG strand (optional)

Where l<N> encodes the strand length (N sugars, N/2 disaccharide repeats).
At least one PG PDB must be present.

Generated outputs:
    custom_files/<pg>_seq.str         CHARMM sequence stream
    custom_files/<pg>_patch.str       CHARMM patch stream
    pg_vars_donor.str                 variables for donor NPG build
    pg_vars_acceptor.str              variables for acceptor NPG build
    rename_donor_segments.str         renames PA## -> PD## (if donor present)
    assemble_sim.inp                  sim-specific assembly script (hardcoded paths)
    <sim_folder>_export/run.sh        ordered shell commands to execute in CHARMM
"""

import sys
import os
import glob
import re


# ── helpers ───────────────────────────────────────────────────────────────────

def pg_name_to_repeats(pg_name):
    """Parse l<N> → number of disaccharide repeats (N/2)."""
    m = re.match(r"l(\d+)$", pg_name)
    if not m:
        sys.exit(f"Error: cannot parse PG strand name '{pg_name}' (expected l<N>)")
    n = int(m.group(1))
    if n % 2 != 0:
        sys.exit(f"Error: PG strand name '{pg_name}' has odd sugar count")
    return n // 2


def write_seq_patch(pg_name, num_repeats, custom_dir):
    """Write <pg>_seq.str and <pg>_patch.str into custom_dir."""
    num_sugars = num_repeats * 2
    num_resi   = num_sugars + 1

    seq_path   = os.path.join(custom_dir, f"{pg_name}_seq.str")
    patch_path = os.path.join(custom_dir, f"{pg_name}_patch.str")

    # Additional disaccharide rows in the glycan sequence (one per repeat beyond the first)
    gly_lines = "\n".join(["BNAM BNAG"] * (num_repeats - 1))

    pep_blocks   = []
    patch_blocks = []
    for j in range(2, num_repeats + 1):
        pep_blocks.append(f"""\
! Read peptide stem {j} sequence
read sequence card
* Peptide sequence
*
4
ADGG MDAP DALA DALA
generate PA{j:02} first none last CTER setup warn

""")
        patch_blocks.append(f"""\
! Apply patches for L{2*j}
patch 14BB   GLY {2*j-1}  GLY {2*j}   setup warn
patch 14BB   GLY {2*j}    GLY {2*j+1} setup warn
patch 3BMDPx GLY {2*j}    PA{j:02} 1  setup warn

""")

    seq_txt = f"""\
* Stream file for {pg_name}, {num_repeats} repeats
* Generated by setup_sim.py

read sequence card
* Glycan Sequence
*
{num_resi}
UNDP ANAM BNAG
{gly_lines}
generate GLY setup first none last none

! Read peptide stem 1 sequence
read sequence card
* Peptide sequence
*
4
ADGG MDAP DALA DALA
generate PA01 first none last CTER setup warn

{"".join(pep_blocks)}\
"""

    patch_txt = f"""\
! Apply patches for L2
patch LLLX   GLY 2  GLY 1   setup warn
patch 14BB   GLY 2  GLY 3   setup warn
patch 3BMDPx GLY 2  PA01 1  setup warn

{"".join(patch_blocks)}\
"""

    with open(seq_path,   "w") as f:
        f.write(seq_txt)
    with open(patch_path, "w") as f:
        f.write(patch_txt)

    return seq_path, patch_path


def write_pg_vars(role, pg_name, num_repeats, pdb_fn,
                  export_dir, sim_name, custom_dir):
    """Write pg_vars_{role}.str; returns (vars_filename, built_prefix)."""
    num_sugars = num_repeats * 2
    exportfn   = f"{sim_name}_{role}"   # base name only (no directory)
    seq_fn     = os.path.join(custom_dir, f"{pg_name}_seq.str"  ).replace("\\", "/")
    patch_fn   = os.path.join(custom_dir, f"{pg_name}_patch.str").replace("\\", "/")

    txt = f"""\
*Information about system - {role} ({pg_name})
*
set PGNAME       = {pg_name}
set SEQFILENAME  = {seq_fn}
set PATCHFILENAME = {patch_fn}
set NUMREPEATS   = {num_repeats}
set NUMSUGARS    = {num_sugars}
set PDBFILENAME  = {pdb_fn}
set EXPORTDIR    = {export_dir}
set EXPORTFN     = {exportfn}
"""
    vars_file = f"pg_vars_{role}.str"
    with open(vars_file, "w") as f:
        f.write(txt)

    built_prefix = f"{export_dir}/{exportfn}"
    return vars_file, built_prefix


def write_rename_donor(num_repeats):
    """Write rename_donor_segments.str: PA## -> PD## for each peptide stem."""
    lines = [
        "* Rename donor peptide stems PA## -> PD## to avoid segid collision with acceptor",
        "*",
    ]
    for j in range(1, num_repeats + 1):
        lines.append(f"rename segid PD{j:02} sele segid PA{j:02} end")
    with open("rename_donor_segments.str", "w") as f:
        f.write("\n".join(lines) + "\n")


def write_assembly_inp(protein_fn, donor_fn, acceptor_fn,
                       export_dir, assembled_fn):
    """
    Generate assemble_sim.inp with hardcoded paths.
    Only includes sections for the components that are actually present.
    """
    out_base = f"{export_dir}/{assembled_fn}"
    lines = [
        "* Assemble protein + PG components",
        "* Generated by setup_sim.py",
        "*",
        "",
        "! --- Topology/parameters ---",
        "stream toppar.str",
        "",
        "! === Protein ===",
        f"open unit 31 read card name {protein_fn}.psf",
        "read psf card unit 31",
        f"open unit 31 read card name {protein_fn}.crd",
        "read coor card unit 31",
        "",
    ]

    unit = 41
    if donor_fn:
        lines += [
            "! === Donor PG ===",
            f"open unit {unit} read card name {donor_fn}.psf",
            f"read psf card unit {unit} append",
            f"open unit {unit} read card name {donor_fn}.crd",
            f"read coor card unit {unit} append",
            "rename segid GLYD sele segid GLY end",
            "stream rename_donor_segments.str",
            "",
        ]
        unit += 10

    if acceptor_fn:
        lines += [
            "! === Acceptor PG ===",
            f"open unit {unit} read card name {acceptor_fn}.psf",
            f"read psf card unit {unit} append",
            f"open unit {unit} read card name {acceptor_fn}.crd",
            f"read coor card unit {unit} append",
            "rename segid GLYA sele segid GLY end",
            "",
        ]

    lines += [
        "print coor",
        "print psf",
        "",
        "! === Write outputs ===",
        f"open write unit 61 card name {out_base}.psf",
        "write psf  card unit 61",
        "close unit 61",
        "",
        f"open write unit 62 card name {out_base}.crd",
        "write coor card unit 62",
        "close unit 62",
        "",
        f"open write unit 63 card name {out_base}.pdb",
        "write coor pdb unit 63",
        "close unit 63",
        "",
        "bomlev -1",
        "",
        "coor orient",
        "coor stat sele all end",
        "",
        "! Molecular Volume",
        "calc dcel = 0.5",
        "calc xdim = int ( ( ?xmax - ?xmin + 5.0 ) / @dcel ) + 1",
        "calc ydim = int ( ( ?ymax - ?ymin + 5.0 ) / @dcel ) + 1",
        "calc zdim = int ( ( ?zmax - ?zmin + 5.0 ) / @dcel ) + 1",
        "calc space = @xdim * @ydim * @zdim",
        "",
        "calc maxint = 2**32 / 2 - 1",
        "if space .gt. @maxint calc space = @maxint",
        "",
        "scalar wmain = radius",
        "scalar wmain add 1.4",
        "scalar 1 = wmain",
        "scalar 2 set 6",
        "coor volume hole space @space sele .not. resname TIP3 end",
        "set molvol = ?volume",
        "",
        "calc cgtot = int ( ?cgtot )",
        "",
        f"open write unit 90 card name {out_base}.str",
        "write title unit 90",
        "* set ncharge = @cgtot",
        "* set xmax = ?xmax",
        "* set ymax = ?ymax",
        "* set zmax = ?zmax",
        "* set xmin = ?xmin",
        "* set ymin = ?ymin",
        "* set zmin = ?zmin",
        "* set molvol = @molvol",
        "*",
        "",
        "stop",
    ]

    with open("assemble_sim.inp", "w") as f:
        f.write("\n".join(lines) + "\n")


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: python setup_sim.py <sim_folder>")

    sim_folder = sys.argv[1].rstrip("/\\")
    if not os.path.isdir(sim_folder):
        sys.exit(f"Error: '{sim_folder}' is not a directory")

    sim_name = os.path.basename(sim_folder)

    # ── detect protein ────────────────────────────────────────────────────────
    psf_files = glob.glob(os.path.join(sim_folder, "*_cg.psf"))
    if not psf_files:
        sys.exit(f"Error: no *_cg.psf found in '{sim_folder}'")
    if len(psf_files) > 1:
        sys.exit(f"Error: multiple *_cg.psf files found: {psf_files}")

    protein_fn = psf_files[0][:-4].replace("\\", "/")   # strip .psf extension
    print(f"Protein:  {protein_fn}.psf / .crd")

    # ── detect donor / acceptor ───────────────────────────────────────────────
    def detect_pg(glob_pattern, role):
        files = glob.glob(os.path.join(sim_folder, glob_pattern))
        if not files:
            return None, None
        if len(files) > 1:
            sys.exit(f"Error: multiple {role} PDB files found: {files}")
        pdb = files[0].replace("\\", "/")
        m = re.search(rf"_{role}_(l\d+)\.pdb$", pdb)
        if not m:
            sys.exit(f"Error: cannot parse PG name from '{pdb}'")
        pg_name = m.group(1)
        print(f"{role.capitalize():8s}: {pdb}  ({pg_name})")
        return pdb, pg_name

    donor_pdb,    donor_pg    = detect_pg("*_donor_l*.pdb",    "donor")
    acceptor_pdb, acceptor_pg = detect_pg("*_acceptor_l*.pdb", "acceptor")

    if not donor_pdb and not acceptor_pdb:
        sys.exit("Error: no PG PDB files found (*_donor_l*.pdb or *_acceptor_l*.pdb)")

    # ── prepare output directory ──────────────────────────────────────────────
    export_dir = f"{sim_folder}_export"
    os.makedirs(export_dir, exist_ok=True)
    os.makedirs("custom_files", exist_ok=True)
    print(f"Export:   {export_dir}/")

    # ── generate seq/patch files and pg_vars for each PG ─────────────────────
    run_cmds = [
        "#!/bin/bash",
        f"# Run script for {sim_name}",
        "# Generated by setup_sim.py",
        "# Execute from the nascentPG_charmm working directory",
        "",
    ]

    donor_built_fn    = None
    acceptor_built_fn = None

    for role, pg_name, pdb_fn in [
        ("donor",    donor_pg,    donor_pdb),
        ("acceptor", acceptor_pg, acceptor_pdb),
    ]:
        if pg_name is None:
            continue

        num_repeats = pg_name_to_repeats(pg_name)
        write_seq_patch(pg_name, num_repeats, "custom_files")
        print(f"  Wrote custom_files/{pg_name}_seq.str  custom_files/{pg_name}_patch.str")

        vars_file, built_prefix = write_pg_vars(
            role, pg_name, num_repeats, pdb_fn, export_dir, sim_name, "custom_files"
        )
        print(f"  Wrote {vars_file}  (output prefix: {built_prefix})")

        if role == "donor":
            donor_built_fn = built_prefix
            write_rename_donor(num_repeats)
            print("  Wrote rename_donor_segments.str")
        else:
            acceptor_built_fn = built_prefix

        out_log = f"{export_dir}/build_{role}.out"
        run_cmds += [
            f"# ── Build {role} PG ({pg_name}) ──",
            f"cp {vars_file} pg_vars.str",
            f"charmm < build_NPG.inp > {out_log}",
            "",
        ]

    # ── generate assembly script ──────────────────────────────────────────────
    assembled_fn = f"{sim_name}_assembled"
    write_assembly_inp(
        protein_fn, donor_built_fn, acceptor_built_fn, export_dir, assembled_fn
    )
    print("  Wrote assemble_sim.inp")

    asm_log = f"{export_dir}/assemble.out"
    run_cmds += [
        "# ── Assemble components ──",
        f"charmm < assemble_sim.inp > {asm_log}",
        "",
        f"echo 'Done.  Check {export_dir}/{assembled_fn}.pdb'",
    ]

    run_sh = os.path.join(export_dir, "run.sh")
    with open(run_sh, "w") as f:
        f.write("\n".join(run_cmds) + "\n")

    print(f"\nAll files generated.  Review and run:")
    print(f"    bash {run_sh}")


if __name__ == "__main__":
    main()
